### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by hlobil** [timonson/gentle_rpc#1]
Do you have plans to add websocket support to your library?

**Comment by timonson** [comment]
Hi @hlobil , unfortunately I don't have much free time at the moment but I would definitely accept pull requests. The next time I find myself in the need of websockets for a project I would probably add support here.

**Comment by timonson** [comment]
Hi @hlobil I implemented a first version of websockets support. I would appreciate it a lot if you would let me know what you think about it from a high level perspective.
