### ISSUE TITLE
"private fields are not currently supported" error in browser

### ISSUE THREAD

**Issue by retog** [timonson/gentle_rpc#7]
With Firefox (89.0) I'm getting the following error message: 

    Uncaught SyntaxError: private fields are not currently supported

Importing the js file created with `deno bundle "https://deno.land/x/gentle_rpc@v2.7/mod.ts"`

**Comment by retog** [comment]
It works using the file from `client/dist/remote.js`.

**Comment by timonson** [comment]
Thanks for reporting @retog . I will add a more browser compatible bundle in the next release. I will also *minify* it.

**Comment by timonson** [comment]
Just for the record, I run the `deno bundle` command with this `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "removeComments": true,
    "lib": ["esnext", "dom", "dom.iterable", "dom.asynciterable", "deno.ns"],
    "experimentalDecorators": true,
    "importsNotUsedAsValues": "preserve",
    "strict": true,
    "noFallthroughCasesInSwitch": false
  }
}
```

To make it compatible with older Safari versions I will run `babel` with the following `babel.config.json`. It transpiles classes and es-modules to compatible JavaScript.

```json
{
  "presets": [
    [
      "@babel/env",
      {
        "modules": false
      }
    ]
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

Then I will use `terser` to minify it.

The emitted JavaScript code will work in browsers going far back but I would welcome additional recommendations.

**Comment by retog** [comment]
Thanks, @timonson!

I'm totally new to deno and haven't found out how `client/dist/remote.js` is generated. Using the pre-generated file the example seems to work.

Unrelated to this issue: do you plan on adding support for more type? Will a method like `'() => { [Symbol.asyncIterator](): AsyncGenerator<{ hostname: string; addresses: string[]; }, void, unknown>; }'`be supported?

**Comment by timonson** [comment]
Hi, I am definitely open to add abstractions. Unfortunately I am not sure if I understand your example/method correctly. Would you mind adding a little bit more context (what is the goal?) or an example to it? Thanks a lot!

**Comment by retog** [comment]
If methods could return async-iterators this would allow for things like live updated news or messaging feeds. Ideally, it would support both iterators of json-objects as well as iterators of `Uint8Array`s for efficient binary applications.

**Comment by timonson** [comment]
In this folder are the compiled files. Only the `http.js` file supports legacy browsers. https://github.com/timonson/gentle_rpc/tree/master/client/dist
